### ISSUE TITLE
xs:sequence in xs:choice is not supported

### ISSUE THREAD

**Issue by MichielCM** [MichielCM/xsd2html2xml#15]

**Comment by MichielCM** [comment]
Fixed in release 3.1.

**Comment by Luca-Colombo** [comment]
Hello Michiel, great work with this project, thank you!
I think that this issue isn't completely closed because I'm having some troubles with the <xs:sequence> inside the <xs:choice> because although the sequences are rendered in the html form, the radio checkbox associated isn't rendered.
I'm using v3.1

Kind regards,
Luca.

**Comment by MichielCM** [comment]
Thanks for the notification. I should never commit without testing... :)

It looks like I forgot to include the $choice variable in the xs:sequence file. In matchers/sequence.xsl, add a parameter to the template: <xsl:param name="choice" />

And pass it in the apply-templates call in the same template: <xsl:with-param name="choice" select="$choice" />

Does that fix the issue?

**Comment by Luca-Colombo** [comment]
Thanks! This in partially fixes the issue but now even every element in the sequence contained in the choice has it's own checkbox.

```xsl
<xs:choice>
	<xs:sequence>
		<xs:element name="CustomerID" />
	</xs:sequence>
	<xs:sequence>
		<xs:element name="Name" />
		<xs:element name="Surname" />
	</xs:sequence>
</xs:choice>
```

With this code, for example, the generated html form has a checkbox for `CustomerID`, `Name` and `Surname` instead of having only two checkboxes: one that enables `CustomerID` and the other one that enables both `Name` and `Surname` fields.

**Comment by Luca-Colombo** [comment]
During my humble tests all went fine after your latest commit, thank you!

**Comment by MichielCM** [comment]
Great, you're welcome! :)
