### ISSUE TITLE
Mandatory Boolean can only be set to "true"

### ISSUE THREAD

**Issue by myrtens** [MichielCM/xsd2html2xml#6]
Hi,

I tried your 30-day evaluation schema form generator with a schema of mine, and discovered what I believe to be a bug. If minOccurs for a type="boolean" is set to 1, your program only lets you set it to "true", otherwise the tag is removed and you cannot save the file.

In addition, I'm not totally convinced that that an invalid file cannot be saved is the best design decision. Besides that, I think your form generator is nice!

**Comment by MichielCM** [comment]
Hi!

Thanks for checking it out.

Yes, it's true that required booleans (either through minOccurs="1" or use="required") have to be checked in order to be valid. This mimicks the 'accept terms and conditions' behavior of checkboxes.

I am not sure if the specification says something about the behavior of required booleans. A simple test with https://www.freeformatter.com/xml-validator-xsd.html showed that required booleans both allow true and false, but they do have to be declared. Perhaps my implementation is too strict...

Saving invalid XML files kind of goes against the purpose of the application... ;) Do you have a use scenario where you'd like to be able to do that?

**Comment by MichielCM** [comment]
Hi, I looked into the documentation and 'false' booleans are indeed valid when required. I updated the source code accordingly. Booleans now can take both values. I'll shortly update the XML Form Generator installer as well.

**Comment by MichielCM** [comment]
Just checking in to say I've released a new version with several features and bug fixes, including the boolean bug you mentioned. Both the GitHub version and the trial download have been updated.
