### ISSUE TITLE
Minor hickups with different XSLT processors

### ISSUE THREAD

**Issue by bmix** [MichielCM/xsd2html2xml#7]
When using *Saxon6.5.5* (an XSLTv1 processor) on `xsd2xhtml.xsl` I get:

> method must be xml, html, or text, or a prefixed name

on `line 30` (the `xsl:output` definition). As far as I know the `xhtml` output method was new in XSL 2.0.

The same happens with MSXML3.0, MSXML4.0 and *Xsltproc*. *Xalan*, however, is fine.

When using *Saxon-HE 9.7.0.19* (v2 processor) this vanishes as well, but this time I get a warning:

> in {false}: The expression is looking or a child element named 'false' - perhaps false() was intended? To            avoid this warning, us child::false or ./false 

on `line: 438, column: 51`, which is `<xsl:with-param name="simple" select="false" />`

Using the other processors, this time including the MS ones, all is fine. This does not seem to break processing (I get a result) but it may introduce some bug deeper inside. I didn't check that far.

EDIT: corrected incorrect claim, that *Xsltproc* does not warn on the `xsl:output`.

**Comment by MichielCM** [comment]
Hi,

Thanks for checking. You're right that xhtml is not a valid output method in XSLT 1.0. I never realized, because most processors don't choke on it. Using xml instead of xhtml does seem to yield similar results, and is a valid option.

The param value should be:
`<xsl:with-param name="simple">false</xsl:with-param>`

I'll update the XSL files with these additions.
